[build]
  command = "npx @11ty/eleventy"
  publish = "_site"

[build.environment]
  NODE_VERSION = "18"
  SANITY_PROJECT_ID = "c7mgn6k7"
  SANITY_DATASET = "production"

[functions]
  directory = "netlify/functions"

[dev]
  command = "npm run start:11ty"
  targetPort = 8080
  port = 8888
  publish = "_site"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/videos/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/webfonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[redirects]]
  from = "/products/*"
  to = "/products/detail/"
  status = 200

[[redirects]]
  from = "/news/:slug/"
  to = "/news/article/?s=:slug"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
